version: '3'

services:
  client: 
    image: client-nextjs-prod
    build: .
    volumes:
      - staticbuild:/app/out
    ports: 
      - "3500:3000"
    networks:
      - prod

networks:
  prod:
    driver: bridge

volumes:
  staticbuild: