version: '3.4'

services:
  backend:
    image: backend-nextjs
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - dev
  
  client: 
    image: client-nextjs
    build: 
      context: ./client
    volumes:
      - staticbuild:/app/out
    networks:
      - dev
  
  nginx:
    image: server-nextjs
    build:
      context: ./nginx
    volumes:
      - staticbuild:/app/public
    ports: 
      - "8080:80"
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild: