version: "3.9"

services:
  webapp:
    build: .
    image: webapp
    container_name: webapp
    ports:
      - "3011:3000"
    volumes:
      - ./app:/urs/src/app
      - /usr/src/app/node_modules
      - /usrc/src/app/.next
      