version: '3.4'

services:
  
  client: 
    image: client-nextjs
    build: .
    volumes:
      - staticbuild:/app/out
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild: