# kubernetes deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        version: IMAGE_LABEL
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp
          image: "${TESTING_IMAGE}"
          imagePullPolicy: IfNotPresent